
#line 3 "lex.conf.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define __yy_create_buffer conf_create_buffer
#define __yy_delete_buffer conf_delete_buffer
#define __yy_flex_debug conf_flex_debug
#define __yy_init_buffer conf_init_buffer
#define __yy_flush_buffer conf_flush_buffer
#define __yy_load_buffer_state conf_load_buffer_state
#define __yy_switch_to_buffer conf_switch_to_buffer
#define __yyin confin
#define __yyleng confleng
#define __yylex conflex
#define __yylineno conflineno
#define __yyout confout
#define __yyrestart confrestart
#define __yytext conftext
#define __yywrap confwrap
#define __yyalloc confalloc
#define __yyrealloc confrealloc
#define __yyfree conffree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define __yyconst const
#else
#define __yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (__yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((__yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE confrestart(confin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(__yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct __yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t __yy_size_t;
#endif

extern __yy_size_t confleng;

extern FILE *confin, *confout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for __yy_rule_can_match_eol because it requires
     *       access to the local variable __yy_act. Since __yyless() is a macro, it would break
     *       existing scanners that call __yyless() from OUTSIDE conflex. 
     *       One obvious solution it to make __yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-conflineno scanner, because __yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                __yy_size_t __yyl;\
                for ( __yyl = n; __yyl < confleng; ++__yyl )\
                    if ( conftext[__yyl] == '\n' )\
                        --conflineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define __yyless(n) \
	do \
		{ \
		/* Undo effects of setting up conftext. */ \
        int __yyless_macro_arg = (n); \
        YY_LESS_LINENO(__yyless_macro_arg);\
		*__yy_cp = (__yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(__yy_c_buf_p) = __yy_cp = __yy_bp + __yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up conftext again */ \
		} \
	while ( 0 )

#define unput(c) __yyunput( c, (__yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct __yy_buffer_state
	{
	FILE *__yy_input_file;

	char *__yy_ch_buf;		/* input buffer */
	char *__yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	__yy_size_t __yy_buf_size;

	/* Number of characters read into __yy_ch_buf, not including EOB
	 * characters.
	 */
	__yy_size_t __yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int __yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int __yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int __yy_at_bol;

    int __yy_bs_lineno; /**< The line count. */
    int __yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int __yy_fill_buffer;

	int __yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via confrestart()), so that the user can continue scanning by
	 * just pointing confin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t __yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t __yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * __yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (__yy_buffer_stack) \
                          ? (__yy_buffer_stack)[(__yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (__yy_buffer_stack)[(__yy_buffer_stack_top)]

/* __yy_hold_char holds the character lost when conftext is formed. */
static char __yy_hold_char;
static __yy_size_t __yy_n_chars;		/* number of characters read into __yy_ch_buf */
__yy_size_t confleng;

/* Points to current character in buffer. */
static char *__yy_c_buf_p = (char *) 0;
static int __yy_init = 0;		/* whether we need to initialize */
static int __yy_start = 0;	/* start state number */

/* Flag which is used to allow confwrap()'s to do buffer switches
 * instead of setting up a fresh confin.  A bit of a hack ...
 */
static int __yy_did_buffer_switch_on_eof;

void confrestart (FILE *input_file  );
void conf_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE conf_create_buffer (FILE *file,int size  );
void conf_delete_buffer (YY_BUFFER_STATE b  );
void conf_flush_buffer (YY_BUFFER_STATE b  );
void confpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void confpop_buffer_state (void );

static void confensure_buffer_stack (void );
static void conf_load_buffer_state (void );
static void conf_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER conf_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE conf_scan_buffer (char *base,__yy_size_t size  );
YY_BUFFER_STATE conf_scan_string (__yyconst char *__yy_str  );
YY_BUFFER_STATE conf_scan_bytes (__yyconst char *bytes,__yy_size_t len  );

void *confalloc (__yy_size_t  );
void *confrealloc (void *,__yy_size_t  );
void conffree (void *  );

#define __yy_new_buffer conf_create_buffer

#define __yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        confensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            conf_create_buffer(confin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->__yy_is_interactive = is_interactive; \
	}

#define __yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        confensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            conf_create_buffer(confin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->__yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->__yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *confin = (FILE *) 0, *confout = (FILE *) 0;

typedef int __yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int conflineno;

int conflineno = 1;

extern char conftext[];

static __yy_state_type __yy_get_previous_state (void );
static __yy_state_type __yy_try_NUL_trans (__yy_state_type current_state  );
static int __yy_get_next_buffer (void );
static void __yy_fatal_error (__yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up conftext.
 */
#define YY_DO_BEFORE_ACTION \
	(__yytext_ptr) = __yy_bp; \
	confleng = (size_t) (__yy_cp - __yy_bp); \
	(__yy_hold_char) = *__yy_cp; \
	*__yy_cp = '\0'; \
	if ( confleng + (__yy_more_offset) >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	__yy_flex_strncpy( &conftext[(__yy_more_offset)], (__yytext_ptr), confleng + 1 ); \
	confleng += (__yy_more_offset); \
	(__yy_prev_more_offset) = (__yy_more_offset); \
	(__yy_more_offset) = 0; \
	(__yy_c_buf_p) = __yy_cp;

#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct __yy_trans_info
	{
	flex_int32_t __yy_verify;
	flex_int32_t __yy_nxt;
	};
static __yyconst flex_int16_t __yy_acclist[132] =
    {   0,
       27,   25,   26,   24,   25,   26,   22,   24,   25,   26,
       21,   25,   26,   24,   25,   26,    1,   24,   25,   26,
       24,   25,   26,   20,   24,   25,   26,   24,   25,   26,
        4,   24,   25,   26,   23,   24,   25,   26,   23,   24,
       25,   26,   23,   24,   25,   26,   23,   24,   25,   26,
       23,   24,   25,   26,   23,   24,   25,   26,   23,   24,
       25,   26,   23,   24,   25,   26,   23,   24,   25,   26,
       23,   24,   25,   26,   23,   24,   25,   26,    3,   25,
       26,    2,   25,   26,    6,    7,    5,    4,    4,   23,
       23,   15,   23,   23,   17,   23,   23,   23,   23,   14,

       23,   23,   16,   23,   23,   23,    4,   23,   19,   23,
       23,   13,   23,   23,   18,   23,   23,   12,   23,    5,
        4,   23,    9,   23,   23,    8,   23,   11,   23,   10,
       23
    } ;

static __yyconst flex_int16_t __yy_accept[74] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
       11,   14,   17,   21,   24,   28,   31,   35,   39,   43,
       47,   51,   55,   59,   63,   67,   71,   75,   79,   82,
       85,   85,   86,   86,   87,   88,   89,   90,   91,   92,
       94,   95,   97,   98,   99,  100,  102,  103,  105,  106,
      107,  107,  108,  108,  109,  111,  112,  114,  115,  117,
      118,  120,  120,  121,  121,  122,  123,  125,  126,  128,
      130,  132,  132
    } ;

static __yyconst flex_int32_t __yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    7,    1,
        1,    8,    9,    1,   10,   11,    8,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,    8,    1,
        8,    1,    1,    1,   13,   14,   14,   14,   15,   16,
       14,   14,   14,   14,   14,   17,   14,   18,   19,   14,
       14,   20,   21,   22,   23,   14,   14,   14,   24,   14,
        1,    1,    1,    8,   25,    1,   26,   14,   14,   14,

       27,   28,   14,   14,   14,   14,   14,   29,   14,   30,
       31,   14,   14,   32,   33,   34,   35,   14,   14,   14,
       36,   14,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static __yyconst flex_int32_t __yy_meta[37] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2
    } ;

static __yyconst flex_int16_t __yy_base[78] =
    {   0,
        0,    0,    0,    0,   99,   98,  100,  103,  103,  103,
      103,   94,  103,   91,  103,   85,   26,    0,   83,   76,
       23,   74,   78,   66,   60,   12,   58,   62,  103,  103,
       83,  103,   80,  103,   31,   32,   37,    0,   69,    0,
       69,    0,   61,   62,   53,    0,   53,    0,   45,   46,
       41,   40,   51,   57,    0,   62,    0,   43,    0,   39,
        0,   53,   52,   50,   45,   41,    0,   27,    0,    0,
        0,  103,   67,   69,   71,   73,   43
    } ;

static __yyconst flex_int16_t __yy_def[78] =
    {   0,
       73,   73,   72,    3,   74,   74,   72,   72,   72,   72,
       72,   75,   72,   76,   72,   72,   72,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   72,   72,
       75,   72,   76,   72,   72,   72,   72,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       72,   72,   72,   77,   77,   77,   77,   77,   77,   77,
       77,   72,   72,   72,   72,   77,   77,   77,   77,   77,
       77,    0,   72,   72,   72,   72,   72
    } ;

static __yyconst flex_int16_t __yy_nxt[140] =
    {   0,
        9,   10,   11,   10,   12,   13,   14,   15,   15,   15,
       16,   17,   18,   18,   18,   19,   18,   20,   21,   18,
       18,   22,   18,   23,    9,   18,   18,   24,   18,   25,
       26,   18,   18,   27,   18,   28,   36,   37,   41,   47,
       42,   48,   35,   52,   38,   51,   53,   36,   37,   62,
       62,   52,   63,   71,   53,   70,   65,   51,   53,   64,
       64,   65,   65,   63,   63,   69,   53,    8,    8,   29,
       29,   31,   31,   33,   33,   68,   67,   66,   61,   60,
       59,   58,   57,   56,   55,   54,   34,   32,   50,   49,
       46,   45,   44,   43,   40,   39,   35,   34,   32,   72,

       30,   30,    7,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72
    } ;

static __yyconst flex_int16_t __yy_chk[140] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,   17,   17,   21,   26,
       21,   26,   35,   36,   77,   35,   36,   37,   37,   51,
       51,   52,   51,   68,   52,   66,   65,   35,   36,   53,
       53,   64,   53,   63,   62,   60,   52,   73,   73,   74,
       74,   75,   75,   76,   76,   58,   56,   54,   50,   49,
       47,   45,   44,   43,   41,   39,   33,   31,   28,   27,
       25,   24,   23,   22,   20,   19,   16,   14,   12,    7,

        6,    5,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72
    } ;

/* Table of booleans, true if rule could match eol. */
static __yyconst flex_int32_t __yy_rule_can_match_eol[27] =
    {   0,
0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 0, 0, 1, 0,     };

extern int conf_flex_debug;
int conf_flex_debug = 0;

static __yy_state_type *__yy_state_buf=0, *__yy_state_ptr=0;
static char *__yy_full_match;
static int __yy_lp;
#define REJECT \
{ \
*__yy_cp = (__yy_hold_char); /* undo effects of setting up conftext */ \
__yy_cp = (__yy_full_match); /* restore poss. backed-over text */ \
++(__yy_lp); \
goto find_rule; \
}

static int __yy_more_offset = 0;
static int __yy_prev_more_offset = 0;
#define __yymore() ((__yy_more_offset) = __yy_flex_strlen( conftext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	(__yy_more_offset) = (__yy_prev_more_offset); \
	confleng -= (__yy_more_offset); \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char conftext[YYLMAX];
char *__yytext_ptr;
#line 1 "conf.l"
/* RTcmix  - Copyright (C) 2004  The RTcmix Development Team
   See ``AUTHORS'' for a list of contributors. See ``LICENSE'' for
   the license to this software and for a DISCLAIMER OF ALL WARRANTIES.
*/

#line 7 "conf.l"
#include "yystype.h"
#include "conf.tab.hpp"
#define __yyterminate() conf_delete_buffer(YY_CURRENT_BUFFER); return YY_NULL
#define YY_DECL int conflex(YYSTYPE *lvalp)
extern int conferror(char *);
#line 591 "lex.conf.c"

#define INITIAL 0
#define INIT 1
#define IGNORE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int __yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int conflex_destroy (void );

int confget_debug (void );

void confset_debug (int debug_flag  );

YY_EXTRA_TYPE confget_extra (void );

void confset_extra (YY_EXTRA_TYPE user_defined  );

FILE *confget_in (void );

void confset_in  (FILE * in_str  );

FILE *confget_out (void );

void confset_out  (FILE * out_str  );

__yy_size_t confget_leng (void );

char *confget_text (void );

int confget_lineno (void );

void confset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int confwrap (void );
#else
extern int confwrap (void );
#endif
#endif

    static void __yyunput (int c,char *buf_ptr  );
    
#ifndef __yytext_ptr
static void __yy_flex_strncpy (char *,__yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int __yy_flex_strlen (__yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int __yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( conftext, confleng, 1, confout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->__yy_is_interactive ) \
		{ \
		int c = '*'; \
		__yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( confin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( confin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, confin))==0 && ferror(confin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(confin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "__yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef __yyterminate
#define __yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) __yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int conflex (void);

#define YY_DECL int conflex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after conftext and confleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register __yy_state_type __yy_current_state;
	register char *__yy_cp, *__yy_bp;
	register int __yy_act;
    
#line 20 "conf.l"

#line 777 "lex.conf.c"

	if ( !(__yy_init) )
		{
		(__yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (__yy_state_buf) )
            (__yy_state_buf) = (__yy_state_type *)confalloc(YY_STATE_BUF_SIZE  );
            if ( ! (__yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in conflex()" );

		if ( ! (__yy_start) )
			(__yy_start) = 1;	/* first start state */

		if ( ! confin )
			confin = stdin;

		if ( ! confout )
			confout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			confensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				conf_create_buffer(confin,YY_BUF_SIZE );
		}

		conf_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		__yy_cp = (__yy_c_buf_p);

		/* Support of conftext. */
		*__yy_cp = (__yy_hold_char);

		/* __yy_bp points to the position in __yy_ch_buf of the start of
		 * the current run.
		 */
		__yy_bp = __yy_cp;

		__yy_current_state = (__yy_start);

		(__yy_state_ptr) = (__yy_state_buf);
		*(__yy_state_ptr)++ = __yy_current_state;

__yy_match:
		do
			{
			register YY_CHAR __yy_c = __yy_ec[YY_SC_TO_UI(*__yy_cp)];
			while ( __yy_chk[__yy_base[__yy_current_state] + __yy_c] != __yy_current_state )
				{
				__yy_current_state = (int) __yy_def[__yy_current_state];
				if ( __yy_current_state >= 73 )
					__yy_c = __yy_meta[(unsigned int) __yy_c];
				}
			__yy_current_state = __yy_nxt[__yy_base[__yy_current_state] + (unsigned int) __yy_c];
			*(__yy_state_ptr)++ = __yy_current_state;
			++__yy_cp;
			}
		while ( __yy_base[__yy_current_state] != 103 );

__yy_find_action:
		__yy_current_state = *--(__yy_state_ptr);
		(__yy_lp) = __yy_accept[__yy_current_state];
goto find_rule; /* Shut up GCC warning -Wall */
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (__yy_lp) && (__yy_lp) < __yy_accept[__yy_current_state + 1] )
				{
				__yy_act = __yy_acclist[(__yy_lp)];
					{
					(__yy_full_match) = __yy_cp;
					break;
					}
				}
			--__yy_cp;
			__yy_current_state = *--(__yy_state_ptr);
			(__yy_lp) = __yy_accept[__yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( __yy_act != YY_END_OF_BUFFER && __yy_rule_can_match_eol[__yy_act] )
			{
			__yy_size_t __yyl;
			for ( __yyl = (__yy_prev_more_offset); __yyl < confleng; ++__yyl )
				if ( conftext[__yyl] == '\n' )
					   
    conflineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( __yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 21 "conf.l"
{ BEGIN IGNORE; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 22 "conf.l"
{ BEGIN INIT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 23 "conf.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "conf.l"
return TOK_NUM;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 25 "conf.l"
return TOK_NUM;
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 26 "conf.l"
return TOK_STRING;
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 27 "conf.l"
return TOK_STRING;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 28 "conf.l"
return TOK_TRUE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 29 "conf.l"
return TOK_TRUE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 30 "conf.l"
return TOK_FALSE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 31 "conf.l"
return TOK_FALSE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 32 "conf.l"
return TOK_TRUE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 33 "conf.l"
return TOK_TRUE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 34 "conf.l"
return TOK_FALSE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 35 "conf.l"
return TOK_FALSE;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 36 "conf.l"
return TOK_TRUE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 37 "conf.l"
return TOK_TRUE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 38 "conf.l"
return TOK_FALSE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 39 "conf.l"
return TOK_FALSE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 40 "conf.l"
return (*conftext);
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 41 "conf.l"
;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 42 "conf.l"
;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 43 "conf.l"
return TOK_KEY;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 44 "conf.l"
conferror((char *) "invalid character");
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 45 "conf.l"
{ BEGIN INIT; unput(conftext[0]); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 46 "conf.l"
ECHO;
	YY_BREAK
#line 1015 "lex.conf.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(INIT):
			case YY_STATE_EOF(IGNORE):
				__yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int __yy_amount_of_matched_text = (int) (__yy_cp - (__yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*__yy_cp = (__yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->__yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed confin at a new source and called
			 * conflex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(__yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->__yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->__yy_input_file = confin;
			YY_CURRENT_BUFFER_LVALUE->__yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for __yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since __yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (__yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf[(__yy_n_chars)] )
			{ /* This was really a NUL. */
			__yy_state_type __yy_next_state;

			(__yy_c_buf_p) = (__yytext_ptr) + __yy_amount_of_matched_text;

			__yy_current_state = __yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * __yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			__yy_next_state = __yy_try_NUL_trans( __yy_current_state );

			__yy_bp = (__yytext_ptr) + YY_MORE_ADJ;

			if ( __yy_next_state )
				{
				/* Consume the NUL. */
				__yy_cp = ++(__yy_c_buf_p);
				__yy_current_state = __yy_next_state;
				goto __yy_match;
				}

			else
				{
				__yy_cp = (__yy_c_buf_p);
				goto __yy_find_action;
				}
			}

		else switch ( __yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(__yy_did_buffer_switch_on_eof) = 0;

				if ( confwrap( ) )
					{
					/* Note: because we've taken care in
					 * __yy_get_next_buffer() to have set up
					 * conftext, we can now set up
					 * __yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(__yy_c_buf_p) = (__yytext_ptr) + YY_MORE_ADJ;

					__yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (__yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(__yy_c_buf_p) =
					(__yytext_ptr) + __yy_amount_of_matched_text;

				__yy_current_state = __yy_get_previous_state(  );

				__yy_cp = (__yy_c_buf_p);
				__yy_bp = (__yytext_ptr) + YY_MORE_ADJ;
				goto __yy_match;

			case EOB_ACT_LAST_MATCH:
				(__yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf[(__yy_n_chars)];

				__yy_current_state = __yy_get_previous_state(  );

				__yy_cp = (__yy_c_buf_p);
				__yy_bp = (__yytext_ptr) + YY_MORE_ADJ;
				goto __yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of conflex */

/* __yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int __yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf;
	register char *source = (__yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (__yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf[(__yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->__yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (__yy_c_buf_p) - (__yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((__yy_c_buf_p) - (__yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->__yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->__yy_n_chars = (__yy_n_chars) = 0;

	else
		{
			__yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->__yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf[number_to_move]),
			(__yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->__yy_n_chars = (__yy_n_chars);
		}

	if ( (__yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			confrestart(confin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->__yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((__yy_size_t) ((__yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->__yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		__yy_size_t new_size = (__yy_n_chars) + number_to_move + ((__yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf = (char *) confrealloc((void *) YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in __yy_get_next_buffer()" );
	}

	(__yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf[(__yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf[(__yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(__yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf[0];

	return ret_val;
}

/* __yy_get_previous_state - get the state just before the EOB char was reached */

    static __yy_state_type __yy_get_previous_state (void)
{
	register __yy_state_type __yy_current_state;
	register char *__yy_cp;
    
	__yy_current_state = (__yy_start);

	(__yy_state_ptr) = (__yy_state_buf);
	*(__yy_state_ptr)++ = __yy_current_state;

	for ( __yy_cp = (__yytext_ptr) + YY_MORE_ADJ; __yy_cp < (__yy_c_buf_p); ++__yy_cp )
		{
		register YY_CHAR __yy_c = (*__yy_cp ? __yy_ec[YY_SC_TO_UI(*__yy_cp)] : 1);
		while ( __yy_chk[__yy_base[__yy_current_state] + __yy_c] != __yy_current_state )
			{
			__yy_current_state = (int) __yy_def[__yy_current_state];
			if ( __yy_current_state >= 73 )
				__yy_c = __yy_meta[(unsigned int) __yy_c];
			}
		__yy_current_state = __yy_nxt[__yy_base[__yy_current_state] + (unsigned int) __yy_c];
		*(__yy_state_ptr)++ = __yy_current_state;
		}

	return __yy_current_state;
}

/* __yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = __yy_try_NUL_trans( current_state );
 */
    static __yy_state_type __yy_try_NUL_trans  (__yy_state_type __yy_current_state )
{
	register int __yy_is_jam;
    
	register YY_CHAR __yy_c = 1;
	while ( __yy_chk[__yy_base[__yy_current_state] + __yy_c] != __yy_current_state )
		{
		__yy_current_state = (int) __yy_def[__yy_current_state];
		if ( __yy_current_state >= 73 )
			__yy_c = __yy_meta[(unsigned int) __yy_c];
		}
	__yy_current_state = __yy_nxt[__yy_base[__yy_current_state] + (unsigned int) __yy_c];
	__yy_is_jam = (__yy_current_state == 72);
	if ( ! __yy_is_jam )
		*(__yy_state_ptr)++ = __yy_current_state;

	return __yy_is_jam ? 0 : __yy_current_state;
}

    static void __yyunput (int c, register char * __yy_bp )
{
	register char *__yy_cp;
    
    __yy_cp = (__yy_c_buf_p);

	/* undo effects of setting up conftext */
	*__yy_cp = (__yy_hold_char);

	if ( __yy_cp < YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register __yy_size_t number_to_move = (__yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->__yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf )
			*--dest = *--source;

		__yy_cp += (int) (dest - source);
		__yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->__yy_n_chars =
			(__yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->__yy_buf_size;

		if ( __yy_cp < YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--__yy_cp = (char) c;

    if ( c == '\n' ){
        --conflineno;
    }

	(__yytext_ptr) = __yy_bp;
	(__yy_hold_char) = *__yy_cp;
	(__yy_c_buf_p) = __yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int __yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(__yy_c_buf_p) = (__yy_hold_char);

	if ( *(__yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* __yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (__yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->__yy_ch_buf[(__yy_n_chars)] )
			/* This was really a NUL. */
			*(__yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			__yy_size_t offset = (__yy_c_buf_p) - (__yytext_ptr);
			++(__yy_c_buf_p);

			switch ( __yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because __yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					confrestart(confin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( confwrap( ) )
						return 0;

					if ( ! (__yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return __yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(__yy_c_buf_p) = (__yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (__yy_c_buf_p);	/* cast for 8-bit char's */
	*(__yy_c_buf_p) = '\0';	/* preserve conftext */
	(__yy_hold_char) = *++(__yy_c_buf_p);

	if ( c == '\n' )
		   
    conflineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void confrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        confensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            conf_create_buffer(confin,YY_BUF_SIZE );
	}

	conf_init_buffer(YY_CURRENT_BUFFER,input_file );
	conf_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void conf_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		confpop_buffer_state();
	 *		confpush_buffer_state(new_buffer);
     */
	confensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(__yy_c_buf_p) = (__yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->__yy_buf_pos = (__yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->__yy_n_chars = (__yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	conf_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (confwrap()) processing, but the only time this flag
	 * is looked at is after confwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(__yy_did_buffer_switch_on_eof) = 1;
}

static void conf_load_buffer_state  (void)
{
    	(__yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->__yy_n_chars;
	(__yytext_ptr) = (__yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->__yy_buf_pos;
	confin = YY_CURRENT_BUFFER_LVALUE->__yy_input_file;
	(__yy_hold_char) = *(__yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE conf_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) confalloc(sizeof( struct __yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in conf_create_buffer()" );

	b->__yy_buf_size = size;

	/* __yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->__yy_ch_buf = (char *) confalloc(b->__yy_buf_size + 2  );
	if ( ! b->__yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in conf_create_buffer()" );

	b->__yy_is_our_buffer = 1;

	conf_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with conf_create_buffer()
 * 
 */
    void conf_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->__yy_is_our_buffer )
		conffree((void *) b->__yy_ch_buf  );

	conffree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a confrestart() or at EOF.
 */
    static void conf_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	conf_flush_buffer(b );

	b->__yy_input_file = file;
	b->__yy_fill_buffer = 1;

    /* If b is the current buffer, then conf_init_buffer was _probably_
     * called from confrestart() or through __yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->__yy_bs_lineno = 1;
        b->__yy_bs_column = 0;
    }

        b->__yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void conf_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->__yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->__yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->__yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->__yy_buf_pos = &b->__yy_ch_buf[0];

	b->__yy_at_bol = 1;
	b->__yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		conf_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void confpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	confensure_buffer_stack();

	/* This block is copied from conf_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(__yy_c_buf_p) = (__yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->__yy_buf_pos = (__yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->__yy_n_chars = (__yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(__yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from conf_switch_to_buffer. */
	conf_load_buffer_state( );
	(__yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void confpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	conf_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((__yy_buffer_stack_top) > 0)
		--(__yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		conf_load_buffer_state( );
		(__yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void confensure_buffer_stack (void)
{
	__yy_size_t num_to_alloc;
    
	if (!(__yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(__yy_buffer_stack) = (struct __yy_buffer_state**)confalloc
								(num_to_alloc * sizeof(struct __yy_buffer_state*)
								);
		if ( ! (__yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in confensure_buffer_stack()" );
								  
		memset((__yy_buffer_stack), 0, num_to_alloc * sizeof(struct __yy_buffer_state*));
				
		(__yy_buffer_stack_max) = num_to_alloc;
		(__yy_buffer_stack_top) = 0;
		return;
	}

	if ((__yy_buffer_stack_top) >= ((__yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (__yy_buffer_stack_max) + grow_size;
		(__yy_buffer_stack) = (struct __yy_buffer_state**)confrealloc
								((__yy_buffer_stack),
								num_to_alloc * sizeof(struct __yy_buffer_state*)
								);
		if ( ! (__yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in confensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((__yy_buffer_stack) + (__yy_buffer_stack_max), 0, grow_size * sizeof(struct __yy_buffer_state*));
		(__yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE conf_scan_buffer  (char * base, __yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) confalloc(sizeof( struct __yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in conf_scan_buffer()" );

	b->__yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->__yy_buf_pos = b->__yy_ch_buf = base;
	b->__yy_is_our_buffer = 0;
	b->__yy_input_file = 0;
	b->__yy_n_chars = b->__yy_buf_size;
	b->__yy_is_interactive = 0;
	b->__yy_at_bol = 1;
	b->__yy_fill_buffer = 0;
	b->__yy_buffer_status = YY_BUFFER_NEW;

	conf_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to conflex() will
 * scan from a @e copy of @a str.
 * @param __yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       conf_scan_bytes() instead.
 */
YY_BUFFER_STATE conf_scan_string (__yyconst char * __yystr )
{
    
	return conf_scan_bytes(__yystr,strlen(__yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to conflex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE conf_scan_bytes  (__yyconst char * __yybytes, __yy_size_t  ___yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	__yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = ___yybytes_len + 2;
	buf = (char *) confalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in conf_scan_bytes()" );

	for ( i = 0; i < ___yybytes_len; ++i )
		buf[i] = __yybytes[i];

	buf[___yybytes_len] = buf[___yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = conf_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in conf_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->__yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void __yy_fatal_error (__yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine __yyless() so it works in section 3 code. */

#undef __yyless
#define __yyless(n) \
	do \
		{ \
		/* Undo effects of setting up conftext. */ \
        int __yyless_macro_arg = (n); \
        YY_LESS_LINENO(__yyless_macro_arg);\
		conftext[confleng] = (__yy_hold_char); \
		(__yy_c_buf_p) = conftext + __yyless_macro_arg; \
		(__yy_hold_char) = *(__yy_c_buf_p); \
		*(__yy_c_buf_p) = '\0'; \
		confleng = __yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int confget_lineno  (void)
{
        
    return conflineno;
}

/** Get the input stream.
 * 
 */
FILE *confget_in  (void)
{
        return confin;
}

/** Get the output stream.
 * 
 */
FILE *confget_out  (void)
{
        return confout;
}

/** Get the length of the current token.
 * 
 */
__yy_size_t confget_leng  (void)
{
        return confleng;
}

/** Get the current token.
 * 
 */

char *confget_text  (void)
{
        return conftext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void confset_lineno (int  line_number )
{
    
    conflineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see conf_switch_to_buffer
 */
void confset_in (FILE *  in_str )
{
        confin = in_str ;
}

void confset_out (FILE *  out_str )
{
        confout = out_str ;
}

int confget_debug  (void)
{
        return conf_flex_debug;
}

void confset_debug (int  bdebug )
{
        conf_flex_debug = bdebug ;
}

static int __yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from conflex_destroy(), so don't allocate here.
     */

    /* We do not touch conflineno unless the option is enabled. */
    conflineno =  1;
    
    (__yy_buffer_stack) = 0;
    (__yy_buffer_stack_top) = 0;
    (__yy_buffer_stack_max) = 0;
    (__yy_c_buf_p) = (char *) 0;
    (__yy_init) = 0;
    (__yy_start) = 0;

    (__yy_state_buf) = 0;
    (__yy_state_ptr) = 0;
    (__yy_full_match) = 0;
    (__yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    confin = stdin;
    confout = stdout;
#else
    confin = (FILE *) 0;
    confout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * conflex_init()
     */
    return 0;
}

/* conflex_destroy is for both reentrant and non-reentrant scanners. */
int conflex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		conf_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		confpop_buffer_state();
	}

	/* Destroy the stack itself. */
	conffree((__yy_buffer_stack) );
	(__yy_buffer_stack) = NULL;

    conffree ( (__yy_state_buf) );
    (__yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * conflex() is called, initialization will occur. */
    __yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef __yytext_ptr
static void __yy_flex_strncpy (char* s1, __yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int __yy_flex_strlen (__yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *confalloc (__yy_size_t  size )
{
	return (void *) malloc( size );
}

void *confrealloc  (void * ptr, __yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void conffree (void * ptr )
{
	free( (char *) ptr );	/* see confrealloc() for (char *) cast */
}

#define YYTABLES_NAME "__yytables"

#line 46 "conf.l"



