#ifndef MAXMSP
#define RTCMIX_NAME "RTcmix"
#define RTCMIX_MAJOR_VERSION "4"
#define RTCMIX_MINOR_VERSION "0"
#define RTCMIX_MICRO_VERSION "1"
#define RTCMIX_VERSION "4.0.1"

#else // MAXMSP
#define RTCMIX_NAME "RTcmix-mm"
#define RTCMIX_MAJOR_VERSION "4"
#define RTCMIX_MINOR_VERSION "0"
#define RTCMIX_MICRO_VERSION "1.8"
#define RTCMIX_VERSION "4.0.1.8"
#endif // MAXMSP
